services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongo:27017/auth-service?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password123
      - JWT_SECRET=dev-jwt-secret-change-in-production-this-is-not-secure
      - JWT_REFRESH_SECRET=dev-refresh-secret-change-in-production-this-is-not-secure
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    depends_on:
      - mongo
      - redis
    networks:
      - auth-network
    restart: unless-stopped
    command: npm run start:dev

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=auth-service
    volumes:
      - mongo_dev_data:/data/db
    networks:
      - auth-network
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass password123
    volumes:
      - redis_dev_data:/data
    networks:
      - auth-network
    restart: unless-stopped

volumes:
  mongo_dev_data:
  redis_dev_data:

networks:
  auth-network:
    driver: bridge
